# Generated by Django 2.0.3 on 2019-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
