# Generated by Django 2.0.3 on 2019-08-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_gear_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Build')),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weaponbuild',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Weapon'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='builds',
            field=models.ManyToManyField(through='bank.WeaponBuild', to='bank.Build'),
        ),
    ]
