# Generated by Django 2.0.3 on 2019-05-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banks',
        ),
        migrations.AlterField(
            model_name='gear',
            name='activeTalent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.ActiveGearTalent'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='activeTalent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.ActiveWeaponTalent'),
        ),
    ]
