# Generated by Django 2.1.5 on 2019-02-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_util'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Util',
        ),
    ]
